server:
  port: 9090

spring:
  application:
    name: learntodrive_auth_service
  data:
    mongodb:
      uri: "mongodb+srv://yashkoltedev:yashkolte@mycluster.igtqr.mongodb.net/?retryWrites=true&w=majority&appName=MyCluster"
      database: drivingschool_user_detail

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

